# Nuotit — Support the development
# Download from the App Store: https://apps.apple.com/app/nuotit-podcasts-and-audio/id6503049956
# Premium subscription or lifetime purchase is the best way to support Nuotit

custom:
  - https://apps.apple.com/app/nuotit-podcasts-and-audio/id6503049956
